bt.addLevel({
	controller: bt.CONTROLLER_LITTLE_MAN_COMPUTER, 
	tank: {
		x:1, y:1, 
		name: "You", color:"rgba(0, 255,0,0.8)", 
		code:"ICAgICAgICAgICAgQlJBIFN0YXJ0DQovLyBEYXRhDQpGb3J3YXJkcyAgICBEQVQgMA0KV2VzdCAgICAgICAgREFUIDYNClNvdXRoICAgICAgIERBVCA0DQpFYXN0ICAgICAgICBEQVQgMg0KTm9ydGhXZXN0ICAgREFUIDcNCkZpcmUgICAgICAgIERBVCAwDQoNCi8vIEluc3RydWN0aW9ucw0KU3RhcnQJICAgIExEQSBGb3J3YXJkcw0KICAgICAgICAJT1VUIDENCiAgICAgICAgCUxEQSBXZXN0DQogICAgICAgIAlPVVQgMg0KICAgICAgICAJTERBIEZvcndhcmRzDQogICAgICAgIAlPVVQgMQ0KICAgICAgICAJTERBIFNvdXRoDQogICAgICAgIAlPVVQgMg0KICAgICAgICAJTERBIEZvcndhcmRzDQogICAgICAgIAlPVVQgMQ0KICAgICAgICAJT1VUIDENCiAgICAgICAgCU9VVCAxDQogICAgICAgIAlPVVQgMQ0KICAgICAgICAJTERBIEVhc3QNCiAgICAgICAgCU9VVCAyDQogICAgICAgIAlMREEgRm9yd2FyZHMNCiAgICAgICAgCU9VVCAxDQogICAgICAgIAlPVVQgMQ0KICAgICAgICAJT1VUIDENCiAgICAgICAgCUxEQSBXZXN0DQogICAgICAgIAlPVVQgMg0KICAgICAgICAJTERBIEZvcndhcmRzDQogICAgICAgIAlPVVQgMQ0KICAgICAgICAJTERBIE5vcnRoV2VzdA0KICAgICAgICAJT1VUIDMNCiAgICAgICAgCUxEQSBGaXJlDQogICAgICAgIAlPVVQgNA0KICAgICAgICAgICAgSExUDQo="
		}, 
	title: "Level 4", 
	description:"Add to the Little Man Computer program to guide the tank to destroy the enemy tank",
	tasks:[
		[0, 0, bt.ITEM_TYPE_CHECKPOINT, bt.ACTION_COLLECT],
		[0, 4, bt.ITEM_TYPE_CHECKPOINT, bt.ACTION_COLLECT],
		[3, 4, bt.ITEM_TYPE_FUEL, bt.ACTION_COLLECT],
		[3, 3, bt.ITEM_TYPE_WATER, bt.ACTION_STATIC],
		[4, 3, bt.ITEM_TYPE_WATER, bt.ACTION_STATIC],
		[5, 3, bt.ITEM_TYPE_WATER, bt.ACTION_STATIC],
		[1, 3, bt.ITEM_TYPE_MINE, bt.ACTION_DESTROY],
		[5, 5, bt.ITEM_TYPE_STRAW, bt.ACTION_DESTROY],
		[5, 4, bt.ITEM_TYPE_TANK, bt.ACTION_DESTROY, {name:"Enemy", color:"rgba(255,0,0,0,0.8)", commands:"", code:""}]
	]
});